# Generated by Django 3.1.6 on 2021-04-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postname', models.CharField(max_length=50)),
                ('mainphoto', models.ImageField(blank=True, null=True, upload_to='')),
                ('contents', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='weather',
            name='day',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
